### ISSUE TITLE
2019-07-22 Microservices Monday

### ISSUE THREAD

**Issue by izumin5210** [wantedly/microservices_monday#50]
2019-07-22 19:00~20:00

Microservices Mondayは、マイクロサービスに関連する話を気軽に共有する会です。毎週月曜日に開催されます。

社外からの参加を想定しているため、レポジトリはpublicになっています。

次のようなポリシーを掲げて開催しています。

- 事前の準備をがんばらない
- 途中参加・途中退席は自由
- 毎週やる

話したい・聞きたいネタを書いていきます ✏️

ネタに困ったときは

- Kubecon/CloudNativeCon のリストを眺める
- [Microservice Weekly](https://microserviceweekly.com/) を眺める

ハッシュタグ [#microservices_monday](https://twitter.com/hashtag/microservices_monday?src=hash)

**Comment by izumin5210** [comment]
> Democratizing Data Analysis with Google BigQuery
> https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/democratizing-data-analysis-with-google-bigquery.html

**Comment by izumin5210** [comment]
> https://arxiv.org/abs/1905.04648 Netflix の Chaos Engineering

**Comment by izumin5210** [comment]
> https://www.infoq.com/news/2018/06/linkedout-failure-injection/
> Chaos Engineering at LinkedIn: The “LinkedOut” Failure Injection Testing Framework

**Comment by izumin5210** [comment]
マイクロサービス開発支援ツール
いい名前
https://github.com/eko/monday

**Comment by izumin5210** [comment]
> BPF Performance Tools: Linux System and Application Observability (book)
> http://www.brendangregg.com/blog/2019-07-15/bpf-performance-tools-book.html

**Comment by luvtechno** [comment]
> > Democratizing Data Analysis with Google BigQuery
> > https://blog.twitter.com/engineering/en_us/topics/infrastructure/2019/democratizing-data-analysis-with-google-bigquery.html

読んだけど直接的に参考になることは書いてなかった。

一言だけ言及されている、 GCP  の Data Catalog が何ができるのか気になる。

https://cloud.google.com/data-catalog/

> Data Catalog is a fully managed and scalable metadata management service that empowers organizations to quickly discover, manage, and understand all their data in Google Cloud

**Comment by izumin5210** [comment]
https://github.com/eko/monday 触ってみた
だいたい↓のような設定ファイルを書いておくことになる

<details>

<summary>設定ファイル例</summary>

```yaml
<: &k8s-context k8s.example.com

<: &accounts-k8s
  name: accounts
  type: kubernetes
  values:
    context: *k8s-context
    namespace: accounts
    labels:
      role: web
    ports:
    - 3002:8080

<: &options-k8s
  name: options
  type: kubernetes
  values:
    # ...

<: &yashima-updates-local
  name: yashima-updates
  path: github.com/wantedly/yashima-updates
  executable: go
  args: ['run', './cmd/server']
  setup:
  - git clone https://github.com/wantedly/yashima-updates.git ~/src/github.com/wantedly/yashima-updates
  - cd ~/src/github.com/wantedly/yashima-updates
  - ./script/bootstrap

<: &yashima-updates-contents-local
  name: yashima-updates-contents
  path: ~/src/github.com/wantedly/yashima-updates-contents
  executable: ./script/server
  setup:
    # ...

projects:
- name: people/updates
  local:
  - *yashima-updates-local
  - *yashima-updates-contents-local
  forward:
  - *accounts-k8s
  - *options-k8s

- name: visit/project
  local:
  - *visit-project-server-local
  - *visit-admin-frontend-local
  forward:
  - *wantedly-k8s
  - *users-rails-k8s
```

</details>

解決してくれる問題

- 「いまコードを書きたいサーバ」「コードは書かないけど依存はしているサーバ」をコマンド1発でうまく起動できる
    - 前者はローカルで起動
    - 後者は開発用 k8s クラスタから port-forwarding
- 開発中のサービス間通信の URL はすべて localhost に統一できる

<details>

<summary>雑感</summary>

- 設定ファイルはぱっとみ超長いけど、大部分は自動生成できそう
    - 上のサンプルのうち、 `*-k8s` の定義 や `setup` section など
    - ファイルを分割して管理できるので、GitHub においておいてみんなで共有する ということが可能
        - e.g.
          - `~/monday.(k8s|local).yaml` -> 自動生成
          - `~/monday.projects.yaml` -> 人間が書く
          - `~/monday.secrets.yaml` -> なんかうまいこと取ってくる
- 本質（？）は `proejcts` section
    - 「開発したいドメインが直接関連するサービス」「それが依存するサービス」のリストを記述し、前者をローカルで起動・後者を k8s から port forward させる ということができる
    - ```yaml
      projects:
      - name: people/updates
        # ...

      - name: visit/project
        local:
        - *visit-project-server-local
        - *visit-admin-frontend-local
        forward:
        - *wantedly-k8s
        - *users-rails-k8s
      ```
- 開発中のサービス間通信はすべて `localhost:....` に向ければ良くなる
    - 「このサーバは k8s の共有サーバを使いたいから URL 書き換えて…」みたいなことをしなくて良くなる
    - Wantedly 社内では共通ライブラリでサービス間通信の URL をうまく扱える仕組みがあるので、この点うまみは少ない…
- ローカルで起動するサーバに関して、 `setup` section を書けば「ローカルにまだプロジェクトがない場合に実行するスクリプト」を記述できる
    - New joiner は最初に `monday run people/updates` を実行するだけで、People Updates の開発に参加できる みたいな世界観になる
- `hostname` 指定すれば、サーバが待ち受ける hostname を指定できる
    - が、たとえば「`updates.wantedly.local` を `localhost:3022` に proxy する」みたいな高度なことをするわけではない
    - あくまで `/etc/hosts` を書き換えるだけ
- proxy 機能もあるので、たとえば「RDS にある開発用 DB を localhost で参照できるようにする」みたいなことも可能
    - だが、結局ローカルでポート番号を割り当てないといけないので 5432 や 6379 は使えない
    - ランダムでポート番号を割り当てて、`updates-db.wantedly.local:5432` から `localhost:<random_port>` にプロキシする くらいやってくれるとうれしいのに…
- ツール自体まだこなれてない（version も `0.0.x`）ので、たまに panic したりする
- インストールスクリプトが `~/.zshrc` に `alias monday='sudo -E monday` を勝手に追記してくる
    - network を弄るのと、 `/etc/hosts` を書き換えたいため
    - ただ、このせいで root 権限持ちの rails サーバが起動してくることになってエキサイティング

[rid](https://github.com/creasty/rid) や [ery](https://github.com/srvc/ery) の思想・機能を取り込ませることができれば、生産性バク上がりしそうな感触はある

</details>
